### PR TITLE
Added FileStream method, Minor Typos

### PR DESCRIPTION
**Pull request by emmagarland**
Added missing "l" from nuget package install

### CODE REVIEW

**Comment by AlexPoint** [comment]
Thank you for those changes @emmagarland .
Now merged on master!

**Comment by emmagarland** [comment]
Thanks @AlexPoint! 👍

**Comment by emmagarland** [comment]
Hi @AlexPoint - just wondered if you were planning to release a new Nuget package version 1.3.5 with the latest updates? I am using a locally generated package to include the changes at the moment, but thought I'd double check so I can stop using it. Thanks! Emma

**Comment by AlexPoint** [comment]
Hi @emmagarland , the new package (v1.3.5) has been pushed with your latest changes!

**Comment by emmagarland** [comment]
Fab! Thanks Alex!

**Pull request merged**
